### ISSUE TITLE
input of the 'Rationalizer'

### ISSUE THREAD

**Issue by wisebenYang** [zhaoxy92/LIREx#3]
Hi Dr. Zhao,

I have some questions about Rationalizer's input. 
In the paper, "Sp=\<s>Lable\<s>Premise\<s>." 
However, in the codes, "Sp=\<s>Premise `(sents = [' '.join(tp[0]) for _, (tp, lb) in enumerate(batch)])"` .
I am not sure whether there are some problem. Thanks.

**Comment by zhaoxy92** [comment]
Hi, I truly apologize for this late reply. You are right, in the current code, it does have Sp=<s>Premise. By fixing this, you can simply replace line 115 with line 116.  line 116 was commented out for a purpose of experimenting. Hope it helps.

**Comment by zhaoxy92** [comment]
I not sure why the comment above got crossed out... Repeat here: You can fix the issue by replacing line 115 with line 116.
